// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDl7N2gMPRtImEnUrBgZ5dSBp4_2v3Xj58',
    appId: '1:426475784807:web:d1c37ad10025246541a2c2',
    messagingSenderId: '426475784807',
    projectId: 'smart-ac-controller-edf1e',
    authDomain: 'smart-ac-controller-edf1e.firebaseapp.com',
    databaseURL: 'https://smart-ac-controller-edf1e-default-rtdb.firebaseio.com',
    storageBucket: 'smart-ac-controller-edf1e.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDn24aguhA5GKTtgtCJFwSr7wMBiWv44po',
    appId: '1:426475784807:android:260494cf42c8090e41a2c2',
    messagingSenderId: '426475784807',
    projectId: 'smart-ac-controller-edf1e',
    databaseURL: 'https://smart-ac-controller-edf1e-default-rtdb.firebaseio.com',
    storageBucket: 'smart-ac-controller-edf1e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBpOCIASMMNCyXoN1uaiZP1SQk75w_hN9A',
    appId: '1:426475784807:ios:3265d5540e6214f741a2c2',
    messagingSenderId: '426475784807',
    projectId: 'smart-ac-controller-edf1e',
    databaseURL: 'https://smart-ac-controller-edf1e-default-rtdb.firebaseio.com',
    storageBucket: 'smart-ac-controller-edf1e.appspot.com',
    iosClientId: '426475784807-76bapkt3arrd9rkdav97qp7g0pqe5sj4.apps.googleusercontent.com',
    iosBundleId: 'com.example.schoolProjectAcController',
  );
}
